### ISSUE TITLE
unit test test_genaz_raises_taskcat_exception failing on python 3.7.4

### ISSUE THREAD

**Issue by cayblood** [aws-quickstart/taskcat#321]
**Describe the bug**
The unit test `test_genaz_raises_taskcat_exception` seems to be failing when running the unit tests in python 3.7.4. Here is the output:
```
test_genaz_raises_taskcat_exception (test_template_params.TestParamGen) ... [ERROR  ] :!Only 1 az's are available in us-east-1
ok
```
**To Reproduce**
1. `python setup.py test`

**Comment by andrew-glenn** [comment]
@cayblood  - is this an actual test failure, or are you noting that the output prints "Error" ? 

I ask, because that particular test asserts that an exception is raised if 1 AZ is available in a given region and the end-user asked for two.

https://github.com/aws-quickstart/taskcat/blob/0d5004f00303008bb1aec7e7af9de44a8e73a4da/tests/unittest/test_template_params.py#L156-L160

https://github.com/aws-quickstart/taskcat/blob/0d5004f00303008bb1aec7e7af9de44a8e73a4da/tests/unittest/test_template_params.py#L81-L83

**Comment by villasv** [comment]
There's an `ok` right below the error message... :P just sayin

**Comment by andrew-glenn** [comment]
I concur with @villasv. FWIW, before a commit makes it into release/master, unit tests must pass; It's difficult to suppress the error message (right now) because it comes from the function(s) being tested.

**Comment by cayblood** [comment]
Thanks for the clarification. Why then does it also showed one failed test in the summary at the end of the entire test run?

**Comment by andrew-glenn** [comment]
@cayblood - I see it too, it looks like it's with our cfn_lint module. Let me dig into it. That shouldn't have made it through to master.

**Comment by jaymccon** [comment]
with the current release we are running all tests on travis against `3.7.4` and `3.6.9` and they are passing.
