### ISSUE TITLE
Use an AWS::MSK::Cluster resource with taskcat

### ISSUE THREAD

**Issue by asaushkin** [aws-quickstart/taskcat#483]
The AWS::MSK::Cluster cloudformation resource is used for definition of the AWS Managed Kafka with cloudformation. It works pretty well and has an interesting feature; outputs of this resource is only an ARN of the resource.

I want to create a quickstart template project that must be validated with the taskcat. This stack must contain the MSK cluster as ECS tasks as well. And now I am stuck with this. How I can define parameters like brokers, zookeepers for the ECS instances?

I can get these parameters over `aws kafka describe-cluster` command. But as I know there is no way to integrate command output to the taskcat task...

Could you give me a piece of advice about how can I use MSK cluster and ECS tasks configured for this kafka cluster in a single taskcat project?

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-msk-cluster.html

**Comment by andrew-glenn** [comment]
Looking at the return-values of `kafka describe-cluster`, the most obvious candidate would be the ZookeeperConnectString. 

I want to confirm the pain you're experiencing, first...

- Both the MSK Cluster and ECS tasks are launched in the same stack
- Since the MSK Cluster only return an ARN, you don't have an easy way to fetch connection strings and similar info *from the cluster*
- Those same details are needed when provisioning the ECS tasks so they do work with the cluster
- Everything needs to be in the same stack. 

Assuming yes... it's a circular dependency. Passing these extra values as a parameter is not necessary the path forward, as the parameters need to be defined before the stack launches. We have a feature on the roadmap that can take the stack output and use it as a parameter for another stack, but I don't think that'll solve the issue here. You'll still need to get the info from the cluster. Once you have that, you don't necessarily need a stack. 

Moving forward, here's what I recommend (for now).

- An MSK Cluster, as usual
- A lambda that does a 'kafka.describe_cluster' call to fetch the details from the cluster, and return those values back to CFN. We've seen good results with Wait Conditions and data handlers. 
- The ECS tasks are now dependent on both the MSK Cluster and the Lambda and WaitCondition.

However, I'm going to track down a developer advocate on our side and point them to this issue. The return of *just* the ARN is really totally not cool.

**Comment by asaushkin** [comment]
Thanks for your answer! I'll try to do it. But it would really cool if you do transmit this message to responsible people.

**Comment by andrew-glenn** [comment]
Will do!

**Comment by asaushkin** [comment]
@andrew-glenn Would you be so kind, to give me a short example of Wait Conditions and lamda handler?

I've been trying to do it a whole day without success. I made something related to it with custom resources. This code successfully executed as a standalone lambda (if comment in the import of the cfn-response module), but when I run this code as `ZipFile` in the example below then the stack creation is hanging up. But if I remove `aws-sdk` from the lambda code then this code works well. 

```
  MskInfo:
    Type: Custom::MSK
    Properties:
      ServiceToken: !GetAtt MskInfoFunction.Arn
      MskArn: !Ref MskArn
      Brokers: ''

  MskInfoFunction:
    Type: AWS::Lambda::Function
    Properties:
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: nodejs12.x
      Handler: index.handler
      Code:
        ZipFile: >
          var response = require('cfn-response');
          const aws = require('aws-sdk');
          var kafka = new aws.Kafka({apiVersion: '2018-11-14'});
          exports.handler = async (event, context) => {
            var params = {
                ClusterArn: event.ResourceProperties.MskArn
            };
            var bootstrapBrokers = await kafka.getBootstrapBrokers(params).promise();
            var responseData = {Brokers: bootstrapBrokers.BootstrapBrokerString};
            response.send(event, context, response.SUCCESS, responseData);
          };
```

**Comment by asaushkin** [comment]
It was an error in the code snippet above, fortunately, I find the bug. 

@andrew-glenn thanks for the tip. It was really useful to me.
