### ISSUE TITLE
resources fail to create

### ISSUE THREAD

**Issue by tamirrrdorrron** [aws-quickstart/taskcat#489]
Hi there,
We have started using taskcat recently. For the purpose of illustrating the point, I will explain a simple scenario:

1. IAM cloud formation template user exists
2. That cloud formation template has been used to create the IAM user in AWS. Imagine the template to look like this:

**./templates/iam_user.yaml**

AWSTemplateFormatVersion: 2010-09-09
Description: service-abc-user IAM User

Resources:
  User:
    Type: AWS::IAM::User
    Properties:
      UserName: service-abc-user

Outputs:
  UserArn:
    Description: ARN for the Service ABC IAM user
    Export:
      Name: service-abc-user-arn
    Value: !GetAtt User.Arn

3. When we run taskcat, we are getting an error because the resources already exists (the IAM user as well as the Exported name)

Our taskcat file would look like this:

**.taskcat.yaml**

general:
  auth:
    ap-southeast-2:test-auth

project:
  name: cf-service-abc-user
  owner: test@test.com
  regions:
  - ap-southeast-2
tests:
  test-iam-user:
    template: ./templates/iam_user.yaml

It seems that taskcat uses a prefix for the stack name, I was assuming it would do the same with  resources it is trying to create? Ie instead of creating 'service-abc-user' it would create 'tcat-service-abc-user'?

The error looks like this:
service-abc-user already exists in stack arn:aws:cloudformation:ap-southeast-2:00000000000000:stack/service-abc-user-stack/12345-1234-1234-123412351245-12341234

I would have been happy to override the username myself (ie in the .taskcat file specify that the username should be tcat-service-abc-user) but I can't seem to find an option to do that. Have looked at using input files but it seems to be for parameters that are requested to be selected during stack creation where in our case it is not what we would be overriding.

Would appreciate any feedback on this. Are we using the tool incorrectly?

Thank you.
T

**Comment by andrew-glenn** [comment]
@tamirrrdorrron 

Taskcat calls the CloudFormation API, so we have control over the stack name. However, because the resource names are defined _within_ the CFN Template, there's no API call to modify those. To add a prefix to the resource names, we would need to modify the template on the fly. While that is done with the `update-ami` subcommand, it's very prescriptive, and we don't want to force end-users to conform to our opinions on such things. 

To that end, resource names are as-is. If you have a namespace collision, the stack will error (as you've seen). Our general recommendation is to *not* define resource names in CFN unless it's absolutely necessary. Otherwise, remove the conflict. 

HTH
-Andrew

**Comment by tamirrrdorrron** [comment]
Hi Andrew, we will rethink our approach based on your feedback.
Thanks for the reply,
T
