### ISSUE TITLE
Add support for creating IAM resources with custom names

### ISSUE THREAD

**Issue by ntmggr** [aws-quickstart/taskcat#51]
When deploying a cf template which creates IAM resources with custom names we get the following error 

```Requires capabilities : [CAPABILITY_NAMED_IAM]```

The following PR resolves this: #50

**Comment by santiagocardenas** [comment]
If we implement this, it must be a per execution option.

It's normally not advised to use custom names IAM resources for reusable CloudFormation templates. This is because it causes collisions if they are deployed more than once in the same account.

Of course, there are cases where custom named resources are used and make sense, but not for the majority of use cases where taskcat would be involved in.

**Comment by ntmggr** [comment]
So what is the catch on including this no matter what? Will it cause issues if you are not using custom names ?

**Comment by santiagocardenas** [comment]
The catch is that you may think that you are not using custom names in IAM when in fact you may be and think that you could deploy the same CloudFormation template in another region (or really anywhere in the same account), when in fact you cannot.

By not adding that capability, you can avoid those issues right away.

I'm really not completely opposed to adding it if every time you test out in every supported region for the CloudFormation template (which would fail) or if it's made an option that you consciously know that you are creating potential collisions.

**Comment by santiagocardenas** [comment]
And in terms of adding it, you would want to add it as part of the array, that is, you include CAPABILITY_IAM and add on to it CAPABILITY_NAMED_IAM, so that you cover both.
