### ISSUE TITLE
End-User Feature Request: command line parameter to skip  uploading to S3

### ISSUE THREAD

**Issue by agamzn** [aws-quickstart/taskcat#68]
Branching this off from #52: 

"Can you please make this as command line parameter where we skip upload s3 and just test ?"

cc: @pankajvkulkarni

**Comment by avattathil** [comment]
Agree with @jaymccon. This issue is handled but the multi-threaded s3 upload jay added. https://github.com/aws-quickstart/taskcat/commit/187fc3d4160e0ef97c811a9daff31594c41b9685

Closing..

**Comment by matteofigus** [comment]
Hi, I would like to reopen this issue.
My project is pretty big, and the structure looks like 

* /ci (taskcat stuff)
* /src (lambdas, cloudformation with macros, frontend, node_modules 🕺 for a total of ~512MB)
* /templates (containing a distributable final cloudformation template produced after a build step)

If the src seems big, consider that anyone doing any frontend or node is likely to be in that scenario, as it is a quite common practice to have the node dependencies locally installed and gitignored (probably symlinked with modern node package managers, but I think that's unrelevant given what the [s3 sync does](https://github.com/aws-quickstart/taskcat/blob/master/taskcat/s3_sync.py#L45))

At the moment, I am hacking around that and removing the `src` folder in my ci pipeline just before running taskcat, but this is less than ideal given taskcat shouldn't care (as far as I understand) about anything that is not in `ci` and `templates`.

1) Can I ask you what's the reason for uploading the whole code to S3?
2) Assuming there is still a valid reason for that, would you be ok on my contributing to this issue with a Pull Request? My initial thinking is that

    a) we could have an option to just include the template and ci to s3 sync: `--skip-s3-sync`
    b) Like (a), but make that the default and sync everything as optional: `--s3-sync`
    c) Add an exclude filter: `--exclude src --exclude *.js`

What's your thoughts on that @avattathil @jaymccon @agamzn? 
Thanks a lot 👍

**Comment by agamzn** [comment]
Reopening to have a spirited discussion. 

We upload everything to S3 because CloudFormation launches from S3, so all of the assets need to be in an S3 bucket for the template to reference them. Specifically everything because there's no defined structure from one project to the next - and candidly, enforcing that structure (beyond what we already do) is not a good customer experience in my opinion.

With that said, we're not slinging 512MB of code around for our projects. Relatively speaking, our projects (quickstarts) are pretty light - A series of templates, maybe some custom scripts, a lambda or two. Overall inconsequential. I definitely see the value add in adding flexibility here. 

@matteofigus - PRs are welcome!  Thinking of the blast radius on our end, I think option C could be the least-invasive option. 

`--skip-s3-sync` implies *nothing* is being sent to S3, but templates and ci would be. 
`--s3-sync` turns off uploading to S3 

Here's what I propose: an `--exclude `filter, and a .`taskcat_s3_ignore` file. 

Thoughts? I'm "throwing darts" as I drink my first cup of coffee. :)

**Comment by matteofigus** [comment]
> Thinking of the blast radius on our end, I think option C could be the least-invasive option.

Ok, sounds good to me

> Here's what I propose: an --exclude filter, and a .taskcat_s3_ignore file, same format style as a .gitignore

I like it! I'm happy to put a PR together for that (or possibly 2 separate to keep changes small) 👍 

> how impactful is this for you?

This is currently affecting one project that will be published under `aws-samples`, very similar to a quickstart and still closed-sourced (the taskcat integration is the only remaining piece I would like to sort out before opening up the code base). So, the impact is very low at the moment, but with our team we expect to work on dozens of similar projects during the next 12 months. The plan is to hook taskcat as a pre-release step, so that any template deployment is guaranteed to work on each region before any change.

> What about alowing --exclude "*" --include "*.foo" flags to be passed only if static s3buckets are defined in the ci config?

The issue in allowing both `include` and `exclude` params, from a UX point of view, is that I feel like it could create ambiguity in terms of who wins in case of an overlap. For instance, in case of `--include *.foo --exclude a.*`, would `a.foo` be included or not? 
My personal preference would be to agree about what's the default behaviour (which, reading about @agamzn's mentioned scenario, seems to be "inclusion") and add only a parameter for the opposite behaviour (exclusion). What do you think?

> I think using auto created buckets implies that the source has not been pre staged.

Can I ask you to clarify? Are you proposing that, in case of the bucket being explicitely specified, we consider that the default behaviour should flip from *inclusion by default* to *exclusion by default*?

**Comment by avattathil** [comment]
Can I ask you to clarify? Are you proposing that, in case of the bucket being explicitely specified, we consider that the default behaviour should flip from inclusion by default to exclusion by default?

- Only if the bucket is explicitly defined provide the option to filter what is uploaded during the tests runs, If no filter is applied upload everything (normal behavior)

**Comment by matteofigus** [comment]
> Only if the bucket is explicitly defined provide the option to filter what is uploaded during the tests runs, If no filter is applied upload everything (normal behavior)

I actually disagree. In my case, I like the idea of having a completely ephemeral bucket created and destroyed during test time (I have another one containing my production artifact, and I wouldn't want tests to access that) - so I am not specifying any bucket; but I still would need to exclude some files just because they are just not needed for the tests so I don't want the tests to access that code or copy it to s3.

In addition to it, I believe having a command called "exclude" that just excludes some files independently from the bucket param, allows us to provide a simplified flow and better user experience.

**Comment by avattathil** [comment]
In that case it makes sense to have the filters for all types of buckets. Thanks for explaining.

**Comment by agamzn** [comment]
This was released today in Taskcat `0.8.28`. Resolving!

**Comment by matteofigus** [comment]
Thanks @agamzn!
