### ISSUE TITLE
Crash on AttributeError: 'Namespace' object has no attribute 'stack_prefix'

### ISSUE THREAD

**Issue by nibty** [aws-quickstart/taskcat#91]
I'm getting the following error when running the example project:
```
 taskcat -c sample-taskcat-project/ci/taskcat.yml 
```

```
taskcat -c sample-taskcat-project/ci/taskcat.yml 
Traceback (most recent call last):
  File "/usr/local/bin/taskcat", line 57, in <module>
    main()
  File "/usr/local/bin/taskcat", line 49, in main
    testdata = tcat_instance.stackcreate(taskcat_cfg, test_list, args.stack_prefix)
AttributeError: 'Namespace' object has no attribute 'stack_prefix'
```

**Comment by avattathil** [comment]
@nibty  Please try the latest version, this issue should be fixed in:  https://github.com/aws-quickstart/taskcat/commit/394ff7e7d495b4f27e189c506ee0a6e1e5141a7d
It was mostly due to a ci build error which cause a library mismatch. 



Latest version of taskcat is  `2018.614.74433)`
To upgrade pip version   [ pip3 install --upgrade taskcat]
To upgrade docker version [ docker pull taskcat/taskcat ]

Let me know if the latest version solves the issue

**Comment by nibty** [comment]
This solves the issue. Thank you.
