### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by nikydobrev** [aws-quickstart/taskcat#99]
Running: 
taskcat.py -c one-click-deployment-sitefinity-aws/ci/taskcat.yml
 _            _             _
| |_ __ _ ___| | _____ __ _| |_
| __/ _` / __| |/ / __/ _` | __|
| || (_| \__ \   < (_| (_| | |_
 \__\__,_|___/_|\_\___\__,_|\__|

version 2018.727.211702

[taskcat] :AWS AccountNumber:    [301813288134]
[taskcat] :Authenticated via:    [environment]

[taskcat] :Reading Config form: one-click-deployment-sitefinity-aws/ci/taskcat.yml
[taskcat] |Queing test => taskcat-json
[INFO   ] :Staging Bucket => ndobrev-us-east-1
Traceback (most recent call last):
  File "D:\taskcat\taskcat.py", line 57, in <module>
    main()
  File "D:\taskcat\taskcat.py", line 45, in main
    tcat_instance.stage_in_s3(taskcat_cfg)
  File "D:\taskcat\taskcat\stacker.py", line 484, in stage_in_s3
    print("{}[S3: -> ]{} s3://{}/{}".format(white, rst_color, self.get_s3bucket(), s3keys.get('Key')))
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by avattathil** [comment]
Looks like you are attempting to run taskcat on windows which is not supported. 
Here is a workaround for windows users:
This [cfn template ](https://github.com/aws-quickstart/taskcat/blob/master/installer/ec2/templates/taskcat.template) will deploy an ec2 instance with taskcat pre installed . 

Closing due to unsupported configuration
